/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.0 		*/
/*  Created On : 01-dic.-2020 12:49:19 a. m. 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS Area CASCADE
;

DROP TABLE IF EXISTS Cliente CASCADE
;

DROP TABLE IF EXISTS Contrato CASCADE
;

DROP TABLE IF EXISTS Pago CASCADE
;

DROP TABLE IF EXISTS Parqueadero CASCADE
;

DROP TABLE IF EXISTS Parqueadero_Tarifa CASCADE
;

DROP TABLE IF EXISTS Servicio CASCADE
;

DROP TABLE IF EXISTS Slot CASCADE
;

DROP TABLE IF EXISTS Tarifa CASCADE
;

DROP TABLE IF EXISTS Telefono CASCADE
;

DROP TABLE IF EXISTS Vehiculo CASCADE
;

/* Create Tables */

CREATE TABLE Area
(
	k_area integer NOT NULL,
	q_cuposDisponibles integer NOT NULL,	-- Cantidad de cupos disponibles en el area
	q_cuposTotales integer NOT NULL,	-- Cantidad total de cupos del area
	k_parqueadero integer NOT NULL,	-- Identificador primario de la entidad fuerte (parqueadero)
	q_cupoAutomovil integer NOT NULL,	-- Indica la cantidad de cupos para el tipo de vehiculo: Automovil
	q_cupoCampero integer NOT NULL,	-- Indica la cantidad de cupos para el tipo de vehiculo: Campero
	q_cupoCamioneta integer NOT NULL,	-- Indica la cantidad de cupos para el tipo de vehiculo: Camioneta
	q_cupoPesado integer NOT NULL,	-- Indica la cantidad de cupos para el tipo de vehiculo: Pesado
	q_cupoMotocicleta integer NOT NULL,	-- Indica la cantidad de cupos para el tipo de vehiculo: Motocicleta
	q_cupoBicicleta integer NOT NULL	-- Indica la cantidad de cupos para el tipo de vehiculo: Bicicleta
)
;

CREATE TABLE Cliente
(
	k_cliente integer NOT NULL,	-- Cedula del cliente
	n_nombre varchar(50) NOT NULL,	-- nombres del cliente
	n_apellido varchar(50) NOT NULL,	-- Apellidos del cliente
	n_direccion varchar(50) NOT NULL	-- Dirección del cliente que contiene la información de la calle, carrera y  número
)
;

CREATE TABLE Contrato
(
	k_contrato integer NOT NULL,	-- Identificador primario para cada contrato
	f_fechaInicio date NOT NULL,	-- Fecha de inicio del contrato
	f_fechaFinal date NOT NULL,	-- Fecha de finalizacion del contrato
	v_valorContrato integer NOT NULL,	-- Valor en pesos a pagar por el contrato
	i_estadoContrato char(1) NOT NULL,	-- Identificador para el estado del contrato (A para activo, I para inactivo)
	k_parqueadero integer NULL,
	k_vehiculo varchar(6) NULL,
	k_cliente integer NULL
)
;

CREATE TABLE Pago
(
	k_pago integer NOT NULL,	-- Identificador primario para cada pago
	n_formaPago varchar(50) NOT NULL,	-- Metodo de pago 
	v_valorPagado integer NOT NULL,	-- Valor en pesos pagado
	k_servicio integer NULL
)
;

CREATE TABLE Parqueadero
(
	k_parqueadero integer NOT NULL,	-- Identificador primario del parqueadero
	n_parqueadero varchar(50) NOT NULL,	-- Nombre del parqueadero
	n_localidad varchar(50) NOT NULL,	-- Localidad en la que esta ubicado el parqueadero
	n_nivelServicio numeric(2,1) NOT NULL,	-- Nivel de servicio, dado por el decreto 461 de 2019, el valor esta entre 0.5 y 1
	n_direccion varchar(50) NOT NULL,	-- Dirección del cliente que contiene la información de la calle, carrera y  número
	q_piso integer NOT NULL,	-- Número de pisos del que esta conformado el parqueadero
	i_subterraneo boolean NOT NULL,	-- Indica con un booleano si el parqueadero es subterraneo o no
	q_area integer NOT NULL	-- Número de areas que componen un parqueadero
)
;

CREATE TABLE Parqueadero_Tarifa
(
	k_parqueadero integer NOT NULL,	-- Identificador primario para cada parqueadero
	k_tarifa integer NOT NULL	-- Identificador primario para las diferentes tarifas de los diferentes parqueaderos
)
;

CREATE TABLE Servicio
(
	k_servicio integer NOT NULL,	-- identificador primario para cada servicio
	f_fechaHoraInicio date NOT NULL,	-- Fecha y hora de la entrada del vehiculo
	f_fechaHoraSalida date NULL,	-- Fecha y hora de salida del vehiculo
	k_slot integer NULL,
	k_vehiculo varchar(6) NULL
)
;

CREATE TABLE Slot
(
	k_slot integer NOT NULL,	-- Identificador primario para cada slot o cupo
	i_estado boolean NOT NULL,	-- Identificador para el estado del cupo (false para desocupado, true para ocupado)
	k_area integer NULL,
	k_parqueadero integer NULL
)
;

CREATE TABLE Tarifa
(
	k_tarifa integer NOT NULL,	-- Identificador primario para cada tarifa
	n_tipo varchar(15) NOT NULL,	-- Tipo de vehiculo asociado a la tarifa
	v_tarifa integer NOT NULL,	-- Valor en pesos de la tarifa
	k_parqueadero integer NULL
)
;

CREATE TABLE Telefono
(
	v_telefono integer NOT NULL,	-- Telefono del cliente
	k_cliente integer NOT NULL	-- Cedula del cliente
)
;

CREATE TABLE Vehiculo
(
	k_vehiculo varchar(6) NOT NULL,	-- Matricula del vehiculo
	n_modelo varchar(50) NOT NULL,	-- Modelo del vehiculo
	n_marca varchar(50) NOT NULL,	-- Marca del vehiculo
	n_tipo varchar(15) NOT NULL,	-- Tipo del vehiculo
	n_color varchar(15) NOT NULL	-- Color del vehiculo
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE Area ADD CONSTRAINT PK_Area
	PRIMARY KEY (k_area,k_parqueadero)
;

ALTER TABLE Area ADD CONSTRAINT q_cuposDisponibles CHECK (q_cuposDisponibles>=0)
;

ALTER TABLE Area ADD CONSTRAINT q_cuposTotales CHECK (q_cuposTotales>0)
;

CREATE INDEX IXFK_Area_Parqueadero ON Area (k_parqueadero ASC)
;

ALTER TABLE Cliente ADD CONSTRAINT PK_Cliente
	PRIMARY KEY (k_cliente)
;

ALTER TABLE Contrato ADD CONSTRAINT PK_Contrato
	PRIMARY KEY (k_contrato)
;

ALTER TABLE Contrato ADD CONSTRAINT v_valorContrato CHECK (v_valorContrato>0)
;

ALTER TABLE Contrato ADD CONSTRAINT i_estadoContrato CHECK (i_estadoContrato IN ('A','I'))
;

CREATE INDEX IXFK_Contrato_Cliente ON Contrato (k_cliente ASC)
;

CREATE INDEX IXFK_Contrato_Parqueadero ON Contrato (k_parqueadero ASC)
;

CREATE INDEX IXFK_Contrato_Vehiculo ON Contrato (k_vehiculo ASC)
;

ALTER TABLE Pago ADD CONSTRAINT PK_Pago
	PRIMARY KEY (k_pago)
;

ALTER TABLE Pago ADD CONSTRAINT v_valorPagado CHECK (v_valorPagado>0)
;

CREATE INDEX IXFK_Pago_Servicio ON Pago (k_servicio ASC)
;

ALTER TABLE Parqueadero ADD CONSTRAINT PK_Parqueadero
	PRIMARY KEY (k_parqueadero)
;

ALTER TABLE Parqueadero ADD CONSTRAINT n_nivelServicio CHECK (0.5 <= n_nivelServicio AND n_nivelServicio <= 1)
;

CREATE INDEX IXFK_Parqueadero_Tarifa_Parqueadero ON Parqueadero_Tarifa (k_parqueadero ASC)
;

CREATE INDEX IXFK_Parqueadero_Tarifa_Tarifa ON Parqueadero_Tarifa (k_tarifa ASC)
;

ALTER TABLE Servicio ADD CONSTRAINT PK_Servicio
	PRIMARY KEY (k_servicio)
;

CREATE INDEX IXFK_Servicio_Slot ON Servicio (k_slot ASC)
;

CREATE INDEX IXFK_Servicio_Vehiculo ON Servicio (k_vehiculo ASC)
;

ALTER TABLE Slot ADD CONSTRAINT PK_Slot
	PRIMARY KEY (k_slot)
;

CREATE INDEX IXFK_Slot_Area ON Slot (k_area ASC,k_parqueadero ASC)
;

ALTER TABLE Tarifa ADD CONSTRAINT PK_Tarifa
	PRIMARY KEY (k_tarifa)
;

ALTER TABLE Tarifa ADD CONSTRAINT v_tarifa CHECK (v_tarifa>0)
;

ALTER TABLE Telefono ADD CONSTRAINT PK_Telefono
	PRIMARY KEY (v_telefono)
;

CREATE INDEX IXFK_Telefono_Cliente ON Telefono (k_cliente ASC)
;

ALTER TABLE Vehiculo ADD CONSTRAINT PK_Vehiculo
	PRIMARY KEY (k_vehiculo)
;

ALTER TABLE Vehiculo ADD CONSTRAINT n_tipo CHECK (n_tipo IN ('automovil','campero','camioneta','pesado','motocicleta','bicicleta'))
;

/* Create Foreign Key Constraints */

ALTER TABLE Area ADD CONSTRAINT FK_Area_Parqueadero
	FOREIGN KEY (k_parqueadero) REFERENCES Parqueadero (k_parqueadero) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Contrato ADD CONSTRAINT FK_Contrato_Cliente
	FOREIGN KEY (k_cliente) REFERENCES  Cliente(k_cliente) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Contrato ADD CONSTRAINT FK_Contrato_Parqueadero
	FOREIGN KEY (k_parqueadero) REFERENCES Parqueadero (k_parqueadero) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Contrato ADD CONSTRAINT FK_Contrato_Vehiculo
	FOREIGN KEY (k_vehiculo) REFERENCES Vehiculo (k_vehiculo) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Pago ADD CONSTRAINT FK_Pago_Servicio
	FOREIGN KEY (k_servicio) REFERENCES Servicio (k_servicio) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Parqueadero_Tarifa ADD CONSTRAINT FK_Parqueadero_Tarifa_Parqueadero
	FOREIGN KEY (k_parqueadero) REFERENCES Parqueadero (k_parqueadero) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Parqueadero_Tarifa ADD CONSTRAINT FK_Parqueadero_Tarifa_Tarifa
	FOREIGN KEY (k_tarifa) REFERENCES Tarifa (k_tarifa) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Servicio ADD CONSTRAINT FK_Servicio_Slot
	FOREIGN KEY (k_slot) REFERENCES Slot (k_slot) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Servicio ADD CONSTRAINT FK_Servicio_Vehiculo
	FOREIGN KEY (k_vehiculo) REFERENCES  Vehiculo(k_vehiculo) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Slot ADD CONSTRAINT FK_Slot_Area
	FOREIGN KEY (k_area,k_parqueadero) REFERENCES Area (k_area,k_parqueadero) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Telefono ADD CONSTRAINT FK_Telefono_Cliente
	FOREIGN KEY (k_cliente) REFERENCES Cliente (k_cliente) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE Area
	IS 'Tabla que guardara los datos de las areas que poseen los parqueaderos'
;

COMMENT ON COLUMN Area.q_cuposDisponibles
	IS 'Cantidad de cupos disponibles en el area'
;

COMMENT ON COLUMN Area.q_cuposTotales
	IS 'Cantidad total de cupos del area'
;

COMMENT ON COLUMN Area.k_parqueadero
	IS 'Identificador primario de la entidad fuerte (parqueadero)'
;

COMMENT ON COLUMN Area.q_cupoAutomovil
	IS 'Indica la cantidad de cupos para el tipo de vehiculo: Automovil'
;

COMMENT ON COLUMN Area.q_cupoCampero
	IS 'Indica la cantidad de cupos para el tipo de vehiculo: Campero'
;

COMMENT ON COLUMN Area.q_cupoCamioneta
	IS 'Indica la cantidad de cupos para el tipo de vehiculo: Camioneta'
;

COMMENT ON COLUMN Area.q_cupoPesado
	IS 'Indica la cantidad de cupos para el tipo de vehiculo: Pesado'
;

COMMENT ON COLUMN Area.q_cupoMotocicleta
	IS 'Indica la cantidad de cupos para el tipo de vehiculo: Motocicleta'
;

COMMENT ON COLUMN Area.q_cupoBicicleta
	IS 'Indica la cantidad de cupos para el tipo de vehiculo: Bicicleta'
;

COMMENT ON TABLE Cliente
	IS 'Tabla donde se guardara toda la informacion asociada a un cliente'
;

COMMENT ON COLUMN Cliente.k_cliente
	IS 'Cedula del cliente'
;

COMMENT ON COLUMN Cliente.n_nombre
	IS 'nombres del cliente'
;

COMMENT ON COLUMN Cliente.n_apellido
	IS 'Apellidos del cliente'
;

COMMENT ON COLUMN Cliente.n_direccion
	IS 'Dirección del cliente que contiene la información de la calle, carrera y  número'
;

COMMENT ON TABLE Contrato
	IS 'Tabla donde se guardara toda la informacion relacionada a los contratos (fechas, valor, estado, etc)'
;

COMMENT ON COLUMN Contrato.k_contrato
	IS 'Identificador primario para cada contrato'
;

COMMENT ON COLUMN Contrato.f_fechaInicio
	IS 'Fecha de inicio del contrato'
;

COMMENT ON COLUMN Contrato.f_fechaFinal
	IS 'Fecha de finalizacion del contrato'
;

COMMENT ON COLUMN Contrato.v_valorContrato
	IS 'Valor en pesos a pagar por el contrato'
;

COMMENT ON COLUMN Contrato.i_estadoContrato
	IS 'Identificador para el estado del contrato (A para activo, I para inactivo)'
;

COMMENT ON TABLE Pago
	IS 'Tabla donde se guardara la informacion asociada al pago del servicio'
;

COMMENT ON COLUMN Pago.k_pago
	IS 'Identificador primario para cada pago'
;

COMMENT ON COLUMN Pago.n_formaPago
	IS 'Metodo de pago '
;

COMMENT ON COLUMN Pago.v_valorPagado
	IS 'Valor en pesos pagado'
;

COMMENT ON TABLE Parqueadero
	IS 'Tabla que guardara toda la informacion del parqueadero (nombre, ubicacion, etc)'
;

COMMENT ON COLUMN Parqueadero.k_parqueadero
	IS 'Identificador primario del parqueadero'
;

COMMENT ON COLUMN Parqueadero.n_parqueadero
	IS 'Nombre del parqueadero'
;

COMMENT ON COLUMN Parqueadero.n_localidad
	IS 'Localidad en la que esta ubicado el parqueadero'
;

COMMENT ON COLUMN Parqueadero.n_nivelServicio
	IS 'Nivel de servicio, dado por el decreto 461 de 2019, el valor esta entre 0.5 y 1'
;

COMMENT ON COLUMN Parqueadero.n_direccion
	IS 'Dirección del cliente que contiene la información de la calle, carrera y  número'
;

COMMENT ON COLUMN Parqueadero.q_piso
	IS 'Número de pisos del que esta conformado el parqueadero'
;

COMMENT ON COLUMN Parqueadero.i_subterraneo
	IS 'Indica con un booleano si el parqueadero es subterraneo o no'
;

COMMENT ON COLUMN Parqueadero.q_area
	IS 'Número de areas que componen un parqueadero'
;

COMMENT ON TABLE Parqueadero_Tarifa
	IS 'Tabla de rompimiento para las tablas parqueadero y tarifa'
;

COMMENT ON COLUMN Parqueadero_Tarifa.k_parqueadero
	IS 'Identificador primario para cada parqueadero'
;

COMMENT ON COLUMN Parqueadero_Tarifa.k_tarifa
	IS 'Identificador primario para las diferentes tarifas de los diferentes parqueaderos'
;

COMMENT ON TABLE Servicio
	IS 'Tabla donde se almacenara la informacion asociada a un servicio (fecha y hora de inicio y salida)'
;

COMMENT ON COLUMN Servicio.k_servicio
	IS 'identificador primario para cada servicio'
;

COMMENT ON COLUMN Servicio.f_fechaHoraInicio
	IS 'Fecha y hora de la entrada del vehiculo'
;

COMMENT ON COLUMN Servicio.f_fechaHoraSalida
	IS 'Fecha y hora de salida del vehiculo'
;

COMMENT ON TABLE Slot
	IS 'Tabla que almacenara el estado de cada uno de los cupos de un area'
;

COMMENT ON COLUMN Slot.k_slot
	IS 'Identificador primario para cada slot o cupo'
;

COMMENT ON COLUMN Slot.i_estado
	IS 'Identificador para el estado del cupo (false para desocupado, true para ocupado)'
;

COMMENT ON TABLE Tarifa
	IS 'Tabla donde se guardaran las diferentes asociadas a los diferentes parqueaderos'
;

COMMENT ON COLUMN Tarifa.k_tarifa
	IS 'Identificador primario para cada tarifa'
;

COMMENT ON COLUMN Tarifa.n_tipo
	IS 'Tipo de vehiculo asociado a la tarifa'
;

COMMENT ON COLUMN Tarifa.v_tarifa
	IS 'Valor en pesos de la tarifa'
;

COMMENT ON TABLE Telefono
	IS 'Tabla para el atributo multivalorado de telefono del cliente'
;

COMMENT ON COLUMN Telefono.v_telefono
	IS 'Telefono del cliente'
;

COMMENT ON COLUMN Telefono.k_cliente
	IS 'Cedula del cliente'
;

COMMENT ON TABLE Vehiculo
	IS 'Tabla donde se guardaran todos la informaciona asociada a un vehiculo'
;

COMMENT ON COLUMN Vehiculo.k_vehiculo
	IS 'Matricula del vehiculo'
;

COMMENT ON COLUMN Vehiculo.n_modelo
	IS 'Modelo del vehiculo'
;

COMMENT ON COLUMN Vehiculo.n_marca
	IS 'Marca del vehiculo'
;

COMMENT ON COLUMN Vehiculo.n_tipo
	IS 'Tipo del vehiculo'
;

COMMENT ON COLUMN Vehiculo.n_color
	IS 'Color del vehiculo'
;
